### ISSUE TITLE
Question of the file "sentence.json" for the dataset Yelp and TripAdvisor

### ISSUE THREAD

**Issue by Delicate2000** [megagonlabs/eseBench#1]
Hello, we are extremely interested in your work while we face challenges in generating a "sentence.json" file for the dataset Yelp and TripAdvisor as the "sentence.json" file provided in Wiki and APR. For Yelp, we download "sentence.json" from the given source Link. However, the labeled "entity phrases" in it are different with those in "entity_candidates.txt". For TripAdvisor, we cannot find the "sentence.json" from the given source Link. We have attemptet to run the project "AutoPhrase" with "./auto_phrase.sh" while "AutoPhrase" do not generate the file "sentence.json". Would you please provide the file "sentence.json" or any dict of "entity to sentences" for the dataset Yelp and TripAdvisor. Any response will be grateful.

**Comment by rahmansunny071** [comment]
@rahmansunny071 provide reference to `sentence.json` for Yelp and TripAdvisor datasets.

**Comment by rahmansunny071** [comment]
Issue added to backlog.

**Comment by rahmansunny071** [comment]
@Delicate2000 please reach out to sajjadur@megagon.ai for source or intermediate data.

**Comment by rahmansunny071** [comment]
The issue creator reached out to the authors for intermediate files.

Note that, the `AutoPhrase` repository is not released under any license. Therefore, we are not able to include the `AutoPhrase` project within this repository.

**Comment by rahmansunny071** [comment]
The issue creator reached out to the authors for intermediate files.

Note that, the `AutoPhrase` repository is not released under any license. Therefore, we are not able to include the `AutoPhrase` project within this repository.
